name: Deploy to Kubernetes
on:
  push:
    tags:
      - "v*"
env:
  IMAGE_NAME: "diplops-app"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: raisultan/ycr-push@main
        env:
          KEY_JSON: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          DOCKERFILE_PATH: "./Dockerfile"
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.ref_name }}
      - name: Update app-dp.yaml
        uses: OpsVerseIO/image-updater-action@0.1.0
        with:
          valueFile: 'app-dp.yaml'
          propertyPath: 'spec.template.spec.containers[0].image'
          value: cr.yandex/${{ secrets.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          commitChange: false
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f app-dp.yaml
